FROM ubuntu:18.04
RUN apt update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:bitcoin/bitcoin
RUN apt-get -y update
RUN apt-get -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3
RUN apt-get -y install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
RUN apt-get install -y software-properties-common
RUN apt-get -y install libdb4.8-dev libdb4.8++-dev

COPY . /src

WORKDIR /src

RUN ./autogen.sh
RUN ./configure --disable-gui-tests --with-gui=auto --disable-wallet
RUN make clean
RUN make -j3


